FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.3
RUN ./bin/elasticsearch-plugin install -b https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.8-es7.17.3/ltr-plugin-v1.5.8-es7.17.3.zip
